serve:
	@php artisan serve

install:
	@composer install

generate-key:
	@php artisan key:generate

migrate:
	@php artisan migrate

seed:
	@php artisan db:seed

filament-user:
	@php artisan filament:user